# Generated by Django 3.1.7 on 2021-05-02 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('empid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('gender', models.CharField(default=None, max_length=15, null=True)),
                ('img', models.ImageField(default='None', null=True, upload_to='pics')),
                ('salary', models.IntegerField(default=0, null=True)),
                ('leaves', models.IntegerField(default=0, null=True)),
                ('isadmin', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmpMgrDept',
            fields=[
                ('ID', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('Emp_No', models.CharField(max_length=20)),
                ('Dept_ID', models.PositiveIntegerField(default=0)),
                ('Emp_Name', models.CharField(max_length=50)),
                ('Dept_Name', models.CharField(max_length=30)),
                ('Manager_Name', models.CharField(max_length=50)),
                ('Manager_Email', models.EmailField(max_length=7)),
                ('Manager_Emp_ID', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Manager_Emp_ID', to='ems.employee')),
            ],
        ),
    ]
