# Generated by Django 3.1.7 on 2021-03-23 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='isadmin',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
