# Generated by Django 3.1.7 on 2021-05-02 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0003_applyforleave'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyforleave',
            name='status',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Approveleave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=20)),
                ('leave_type', models.CharField(max_length=30)),
                ('begin_date', models.DateField()),
                ('end_date', models.DateField()),
                ('avial_days', models.IntegerField(default=0, null=True)),
                ('req_days', models.IntegerField(default=0, null=True)),
                ('reason', models.TextField()),
                ('status', models.CharField(max_length=30)),
                ('Mgr_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Mgr_id', to='ems.empmgrdept')),
            ],
        ),
    ]
