# Generated by Django 3.1.7 on 2021-05-03 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0004_auto_20210502_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approveleave',
            name='Mgr_id',
            field=models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, related_name='Mgr_id', to='ems.empmgrdept'),
        ),
    ]
