# Generated by Django 3.1.7 on 2021-05-03 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0006_auto_20210503_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='approveleave',
            name='emp_name',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
    ]
